### ISSUE TITLE
Only the last matching song is displayed in "Artists" tab

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs#113]
In the "Artists" tab, only the last matching song for the respective Author is displayed.
For example, for the author "Berkmans", 52 matching songs were found in the db using the following query:

```
select * from songs a where id in (select song_id from authors_songs where author_id = (select id from authors where display_name = 'Berkmans'))
```
But the app displays only the last matching song.

**Comment by nivas22** [comment]
Yes James. We found the bug. Now we resolved the problem.

Seenivasan Sankaran

**Comment by sskjames** [comment]
I noticed the issue in other tabs (e.g Albums) as well. Please ensure that it works properly in all the tabs.
