### ISSUE TITLE
Search by title or lyrics

### ISSUE THREAD

**Issue by swotge** [crunchersaspire/worshipsongs#152]

**Comment by sskjames** [comment]
The songs table contains a column called "search_title" which is basically a combination of "title" and "alternate title". So if we want to search by title and alternate title, all we need to do is to search by "search_title".

The songs table also has a column named "search_lyrics" which is basically a tokenized form of the lyrics. If we can search by this column, that will help users immensely and they can find the songs for which they don't know the title.

This will also help users who use Tamil keyboard to search in Tamil.

**Comment by sskjames** [comment]
I was able to search by title, alternate title and lyrics using English keyboard. However, I couldn't search in Tamil.

**Comment by swotge** [comment]
The song content in search lyrics field.

```
 y 1 எனக க ய ஜ வன வ ட டவர y enakkaai jeevan vittavarae y 
 என ன ட ர க க எழ ந தவர y ennodirukka ezhunthavarae  y
 என ன என ற ம வழ நடத த வ ர y ennai endrum vazhi nadathuvarae y 
 என ன சந த க க வந த ட வ ர y ennai santhikka vanthiduvaarae  y
 இய ச ப த ம இய ச ப த ம y yesu pothumae yesu pothumae y 
 எந த ந ள ல ம எந ந ல ய ல ம y entha naalilumae ennilaiyilumae y 
 எந தன வ ழ வ ன ல இய ச ப த ம y enthan vazhvinilae yesu pothumae  y 2 
 ப ல ல ள ள இடங கள ல ம ய த த ட வ ர y pullulla idangalil meithiduvaar y 
 அமர ந த தண ண ரண ட நடத த ட வ ர y amarntha thannerandai nadathiduvaar  y 
 ஆத த ம வ ந தம த ற ற ட வ ர y aathumaavai nitham thetriduvaar y 
 மரணப பள ளத த க க ல க த த ட வ ர y marana pallathaakkil kaathiduvaar  y 3
 மன தர என ன க க வ ட ட ல ம y manithar ennai kaivittaalum y 
 ம ம சம அழ க ந ற ட ட ல ம y maamisam azhugi naarittaalum  y 
 ஐஸ வர யம ய வ ம அழ ந த ட ட ல ம y aisvariyam yaavum azhinthittaalum y 
 ஆக தவன என ற தள ள வ ட ட ல ம y aagathavan endru thallivittalum  y 4 
 ப ச ச ன ச தன ப ர க ட ட ல ம y pisaasin soathanai perugittaalum y 
 ச ர ந த ப க மல ம ன ச ல லவ y soarnthu pogaamal mun sellavae  y 
 உலகம ம ம ம சம ம மயக க ட ட ல ம y ulagamum maamisamum mayakitalum y
 மயங க ட மல ம ன ச ல லவ y mayangidaamal mun sellavae
```

Tamil characters is not added properly that is why we couldn't search in tamil

**Comment by sskjames** [comment]
Okay, then I will close this issue.
