### ISSUE TITLE
Fix UI issues in Action Bar and Tab Bar

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs#154]
Action Bar and Tab Bar colours need to be much darker to help the text stand out. Change the Status Bar colour to a even darker shade to adhere to Material Design principles.

Only selected tab in Tab Bar should have white font colour. Other tabs should have a lighter shade of Tab Bar background colour as their font colours.

**Comment by sskjames** [comment]
It looks better now. But if the background is a bit more darker (like the current status bar) it will be awesome.

**Comment by crunchersaspire** [comment]
Issue is resolved. Right now we are using hexcolor(#1ea2fa) for status bar and hexcolor(#1ab3ff) for action bar Can you give color suggestion?
