### ISSUE TITLE
Application crashed while changing from portrait to landscape after opening any dialog box

### ISSUE THREAD

**Issue by pitchumani1989** [crunchersaspire/worshipsongs#176]

**Comment by crunchersaspire** [comment]
Issue is identified in development mode. Thank file the issue

**Comment by sskjames** [comment]
I couldn't recreate this issue. Can someone specify the exact steps to recreate the problem?

**Comment by sskjames** [comment]
I couldn't recreate this issue. Can someone specify the exact steps to recreate the problem?
