### ISSUE TITLE
Black background is displayed in dialog boxes

### ISSUE THREAD

**Issue by pitchumani1989** [crunchersaspire/worshipsongs#177]
What was the ativity?
Open new playlist creation dialog box.

What was observed?
Black color is displayed behind the dialog box
Same problem occured, while opening delete dialog box in playlist.

**Comment by crunchersaspire** [comment]
Issue is identified in development mode. Thank file the issue

**Comment by crunchersaspire** [comment]
This issue recreated in asus mobile only.

**Comment by sskjames** [comment]
I didn't face this in HTC One
