### ISSUE TITLE
Embed and play youtube videos

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs#195]
The app should support embedding and playing youtube videos (to start with).

We can leverage the "comments" column in the "songs" db to define the media url in a property format, for eg:
mediaUrl=https://youtu.be/ijmhcA0W_Bg

The app should render this video in addition to showing the lyrics. The video can be displayed at the bottom in Portrait mode.

NOTE: We can adapt a different layout for landscape mode with the video and lyrics displayed side by side with lyrics taking a larger portion.

**Comment by swotge** [comment]
Below exception got in android monitor when display song content and youtube view in same view

```
10-16 22:19:37.677 14857-14857/org.worshipsongs W/YouTubeAndroidPlayerAPI: YouTube video playback stopped due to unauthorized overlay on top of player. The YouTubePlayerView is not contained inside its ancestor com.google.android.youtube.player.YouTubePlayerView{27d9b047 V.E..... ......ID 0,0-0,0}. The distances between the ancestor's edges and that of the YouTubePlayerView is: left: 0, top: 0, right: 0, bottom: 0 (these should all be positive).
10-16 22:19:38.036 14857-14857/org.worshipsongs W/YouTubeAndroidPlayerAPI: YouTube video playback stopped due to unauthorized overlay on top of player. The YouTubePlayerView is obscured by com.getbase.floatingactionbutton.FloatingActionButton{1df709e3 VFED..C. ........ 572,986-720,1134 #7f0d00aa app:id/play_song_fab}. The view is inside the YouTubePlayerView, with the distance in px between each edge of the obscuring view and the YouTubePlayerVi
```

**Comment by swotge** [comment]
Format to add media url in comments column.
For e.g This is  https://www.youtube.com/watch?v=UFccvtrP1d8 sample youtube url.
Add *mediaurl=UFccvtrP1d8* this is sufficient. No need to add full url.

**Comment by sskjames** [comment]
Maddy, adding the full URL is less error prone. Otherwise the contributors may make mistakes if they were to copy just a portion of it.

Moreover, we may support additional media options like Spotify etc in future.
