### ISSUE TITLE
Vibration is felt twice while long pressing a song

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs#85]
**What was the activity?**
I installed the latest 1.1 SNAPSHOT APK.
I long pressed a song to add it to a service.

**What was observed?**
The vibration effect was felt twice.

**What is expected?**
The vibration effect should be felt once. To understand this, try long pressing an email in the Gmail mobile app.

**Comment by nivas22** [comment]
We can't recreate this issue.
FYI,
We set the vibration effect time for 15 ms, I think so only the vibration effect was little bit more.
but it's not felt twice.  

@sskjames 
We gave the same vibration effect for the Service Page, Service song list page. 
I think, you already check those also.
