### ISSUE TITLE
Phone screen should be awake by default while viewing a song

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs#90]
**What was the activity?**
* Installed 1.1 SNAPSHOT apk.
* Viewed a song.
* Let the phone idle for few seconds

**What was observed?**
* Phone screen was locked after few seconds.

**What is expected?**
Phone screen should be awake by default while songs are viewed.
This is crucial because, singing a song can take as long as 5 minutes and people who are using our app shouldn't be unlocking the phone when the phone goes idle.

**Comment by swotge** [comment]
Issue is identified in development environment
